=== fardanaljihad/api-testing/src/test/resources/testdata/userUpdateData-Schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "gender": {
      "type": "string"
    },
    "email": {
      "type": "string",
      "format": "email"
    },
    "dateOfBirth": {
      "type": "string",
      "format": "date-time"
    },
    "picture": {
      "type": "string",
      "format": "uri"
    },
    "location": {
      "type": "object",
      "properties": {
        "street": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "timezone": {
          "type": "string"
        }
      }
    },
    "registerDate": {
      "type": "string",
      "format": "date-time"
    },
    "updateDate": {
      "type": "string",
      "format": "date-time"
    }
  }
}

=== fardanaljihad/api-testing/src/test/resources/testdata/userUpdateDataTC01-Data.json
{
  "title": "mrs",
  "firstName": "Hasta",
  "lastName": "Lafista",
  "gender": "female",
  "email": "lafista@gmail.com",
  "dateOfBirth": "2003-05-26T08:27:48.279Z",
  "location": {
    "street": "02, sesama street",
    "city": "Cool",
    "state": "Frozen",
    "country": "Antartika",
    "timezone": "0:00"
  }
}
